---
title: "World-Happiness Appendix"
author: "Rylan Marianchuk"
date: "STAT 429 project"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(formatR)
library(knitr)
library(ggplot2)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

## Analysis
# Research question 1

Does there exist statistically significant differences in means of Happiness score across continents? This is approached using a One-Way ANOVA:

The hypothesis test follows the null and alternative:
$$H_0:  \mu_{africa} = \mu_{asia} = \mu_{europe} = \mu_{africa} = \mu_{oceania} = \mu_{NAmerica} = \mu_{SAmerica}$$
$$H_A: \mu_i \neq \mu_j \> \texttt{  for some } i,j$$


```{r }
world.happiness <- read.csv("final.csv")

# ANOVA
table(world.happiness$region)

anova = data.frame("Happiness Score" = world.happiness$happiness.score, "Continents" = world.happiness$region)

summary(aov(Happiness.Score ~ Continents, data = anova))

fit <- lm(Happiness.Score ~ Continents, data = anova)
summary(fit)

summary(lm(Happiness.Score  ~ C(Continents,contr.treatment("Asia")), data=anova ) )

# Results are discussed in report
```

Model diagnostics 

```{r}

```


